#!/usr/bin/env python3
"""Generate the Phosphor name -> codepoint table the firmware icon renderer needs.

Touch v3 renders button icons from a bundled Phosphor weight: the spec carries
{"name": "film-slate", "px": 40} and the firmware resolves the name to a
codepoint through this table. The SAME mapping is embedded by the server (canvas
preview + rasterizer), so both sides MUST be generated from the same pinned
Phosphor release -- a mismatch draws the wrong glyph, which is the exact failure
the contract's version pin exists to prevent.

Source of truth is the per-weight stylesheet already vendored in the server repo
(static/icons/phosphor/<weight>/style.css), whose rules look like:

    .ph-bold.ph-lightbulb:before {
      content: "\\eb9a";
    }

Usage (--version is REQUIRED and is not discoverable from the CSS, which is the
point: nobody should ship an unpinned map):

    tools/gen_phosphor_codepoints.py \\
        --css ../tesserae/static/icons/phosphor/bold/style.css \\
        --version 2.1.0 --weight bold \\
        --out include/phosphor_codepoints.h

Re-run whenever the pinned Phosphor version changes. Never hand-edit the output.
"""

import argparse
import pathlib
import re
import sys

# ".ph-bold.ph-lightbulb:before { content: "\eb9a"; }" -> ("lightbulb", "eb9a")
RULE = re.compile(
    r"\.ph-[a-z0-9-]*\.?ph-([a-z0-9-]+):before\s*\{\s*content:\s*\"\\([0-9a-fA-F]+)\"",
    re.MULTILINE,
)


def parse_css(text):
    """Extract {name: codepoint}. Later duplicates must agree with earlier ones."""
    out = {}
    for name, hexcp in RULE.findall(text):
        cp = int(hexcp, 16)
        if name in out and out[name] != cp:
            raise SystemExit(
                f"conflicting codepoints for '{name}': "
                f"U+{out[name]:04X} vs U+{cp:04X}"
            )
        out[name] = cp
    return out


def emit(icons, version, weight):
    """A sorted table + binary search: compact in flash, no hashing needed."""
    lines = [
        "/* GENERATED by tools/gen_phosphor_codepoints.py -- DO NOT EDIT.",
        " *",
        f" * Phosphor {version}, weight '{weight}'; {len(icons)} icons.",
        " * Must be regenerated from the SAME pinned release the server embeds,",
        " * or the two sides resolve a name to different glyphs (touch-v3",
        " * contract: glyph-identity is the guarantee, not pixel-identity).",
        " */",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f'#define T3_PHOSPHOR_VERSION "{version}"',
        f'#define T3_PHOSPHOR_WEIGHT  "{weight}"',
        "",
        "typedef struct { const char *name; uint32_t cp; } t3_phosphor_entry_t;",
        "",
        "/* Sorted by name for bsearch(). */",
        "static const t3_phosphor_entry_t T3_PHOSPHOR_MAP[] = {",
    ]
    for name in sorted(icons):
        lines.append(f'    {{ "{name}", 0x{icons[name]:04X} }},')
    lines += [
        "};",
        "",
        "#define T3_PHOSPHOR_MAP_LEN "
        f"({len(icons)})",
        "",
    ]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--css", required=True, type=pathlib.Path,
                    help="Phosphor per-weight style.css to parse")
    ap.add_argument("--version", required=True,
                    help="pinned Phosphor release, e.g. 2.1.0 (no default: pin it)")
    ap.add_argument("--weight", default="bold",
                    help="weight the CSS belongs to (default: bold)")
    ap.add_argument("--out", type=pathlib.Path,
                    help="header to write (default: stdout)")
    args = ap.parse_args()

    if not args.css.is_file():
        raise SystemExit(f"no such file: {args.css}")
    icons = parse_css(args.css.read_text(encoding="utf-8", errors="replace"))
    if not icons:
        raise SystemExit(f"no icon rules matched in {args.css} -- format changed?")

    header = emit(icons, args.version, args.weight)
    if args.out:
        args.out.write_text(header, encoding="utf-8")
        print(f"{args.out}: {len(icons)} icons, Phosphor {args.version} "
              f"({args.weight})", file=sys.stderr)
    else:
        sys.stdout.write(header)


if __name__ == "__main__":
    main()
